version: '3'
services:
    mongo-db:
        image: mongo:latest
        ports:
        - "27017:27017"
        command: --smallfiles
    user-management:
        build: ./usermanagementservice .
        ports:
        - "8083:8083"
        links:
        - mongo-db
    charging-point:
        build: ./chargingpointservice .
        ports:
        - "8081:8081"
        links:
        - mongo-db
    environment-info:
        build: ./environmentservice
        ports: 
        - "8082:8082"
        links:
        - mongo-db
        
# YAML-Datei ist verantwortlich f端r das Starten der Ausf端hrungsumgebung. 3 Container werden f端r die Microservices 
# gestartet und ein weiterer Container f端r die Datenbank. Die Microservices werden jeweils mit der Datenbank verlinkt
        
        