version: '3'
services:
    mongo-db:
        image: mongo:latest
        ports:
        - "27017:27017"
        command: --smallfiles
    user-management:
        build: ./usermanagementservice .
        ports:
        - "8083:8080"
        links:
        - mongo-db
    charging-point:
        build: ./chargingpointservice .
        ports:
        - "8081:8081"
        links:
        - mongo-db
    environment-info:
        build: ./environmentservice .
        ports: 
        - "8082:8082"
        links:
        - mongo-db
    common:
        build: ./commonElementsService .
    varnish:
        build: varnish
        ports:
        - "8080:8080"
        links:
        - user-management
        - common
# YAML-Datei für das Starten der Ausführungsumgebung für die Microservices. Enthält zwei weitere Services. Common-Service stellt eine GO-Anwendung
# bereit, die beim Aufruf bestimmter URL´s Funktionen aufruft und HTML-Fragmente bereitstellt. Service varnish dient als ESI-Implementierung. Webcache 
# wertet esi-Tags aus HTML-Dokument aus und ersetzt diese mit HTML-Fragmenten aus dem common-Service. 
        